# citation/exporter.py
# Xuất danh sách bài báo ra các định dạng khác nhau:
# BibTeX (.bib), CSV (.csv), Excel (.xlsx), APA List (.txt)

import io
import re
import csv
from typing import List
from datetime import datetime

import pandas as pd

from core.models import Article
from citation.formatter import format_apa_plain, format_mla, format_chicago


# ---------------------------------------------------------------
# Hàm tiện ích nội bộ
# ---------------------------------------------------------------

def _sanitize_bibtex_key(text: str) -> str:
    """Tạo BibTeX key hợp lệ từ tác giả và năm."""
    text = re.sub(r"[^a-zA-Z0-9_]", "", text.replace(" ", "_"))
    return text[:30]  # Giới hạn độ dài


def _escape_bibtex(text: str) -> str:
    """Escape các ký tự đặc biệt trong BibTeX."""
    if not text:
        return ""
    # Escape & % $ # _ { } ~ ^ \
    replacements = [
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def _format_bibtex_authors(authors: List[str]) -> str:
    """
    Định dạng tác giả theo chuẩn BibTeX: "Last, First and Last2, First2 and ..."
    """
    if not authors:
        return "Unknown Author"

    bib_authors = []
    for author in authors:
        author = author.strip()
        if "," in author:
            # Đã đúng dạng "Last, First"
            bib_authors.append(author)
        else:
            parts = author.split()
            if len(parts) >= 2:
                bib_authors.append(f"{parts[-1]}, {' '.join(parts[:-1])}")
            else:
                bib_authors.append(author)

    return " and ".join(bib_authors)


def _article_to_bibtex(article: Article) -> str:
    """
    Chuyển đổi một Article thành entry BibTeX.
    Hỗ trợ: @article, @inproceedings, @book, @incollection, @misc
    """
    # Xác định loại entry
    entry_type_map = {
        "article": "article",
        "conference": "inproceedings",
        "book": "book",
        "chapter": "incollection",
        "thesis": "phdthesis",
        "report": "techreport",
    }
    entry_type = entry_type_map.get(article.doc_type, "article")

    # Tạo citation key: Author + Year + FirstWordOfTitle
    first_author = ""
    if article.authors:
        a = article.authors[0]
        if "," in a:
            first_author = a.split(",")[0].strip()
        else:
            first_author = a.split()[-1] if a.split() else a

    first_word = ""
    if article.title:
        words = re.sub(r"[^a-zA-Z0-9 ]", "", article.title).split()
        first_word = words[0] if words else ""

    year_str = str(article.year) if article.year else "nd"
    cite_key = _sanitize_bibtex_key(f"{first_author}{year_str}{first_word}")
    if not cite_key:
        cite_key = f"ref_{article.internal_id}"

    # Xây dựng các field
    fields = {}
    fields["title"] = "{" + _escape_bibtex(article.title) + "}"
    fields["author"] = "{" + _format_bibtex_authors(article.authors) + "}"

    if article.year:
        fields["year"] = str(article.year)
    if article.journal and entry_type == "article":
        fields["journal"] = "{" + _escape_bibtex(article.journal) + "}"
    if article.journal and entry_type == "inproceedings":
        fields["booktitle"] = "{" + _escape_bibtex(article.journal) + "}"
    if article.volume:
        fields["volume"] = article.volume
    if article.issue:
        fields["number"] = article.issue
    if article.pages:
        fields["pages"] = article.pages.replace("-", "--")
    if article.publisher:
        fields["publisher"] = "{" + _escape_bibtex(article.publisher) + "}"
    if article.doi:
        fields["doi"] = article.doi
    if article.url:
        fields["url"] = article.url
    if article.abstract:
        # Giới hạn abstract trong BibTeX (300 ký tự)
        abstract_short = article.abstract[:300] + ("..." if len(article.abstract) > 300 else "")
        fields["abstract"] = "{" + _escape_bibtex(abstract_short) + "}"
    if article.fields_of_study:
        fields["keywords"] = "{" + ", ".join(article.fields_of_study[:5]) + "}"
    fields["note"] = f"Source: {article.source}"

    # Render
    field_lines = ",\n  ".join(f"{k} = {v}" for k, v in fields.items())
    return f"@{entry_type}{{{cite_key},\n  {field_lines}\n}}"


# ---------------------------------------------------------------
# Xuất BibTeX
# ---------------------------------------------------------------

def export_bibtex(articles: List[Article]) -> str:
    """
    Xuất danh sách bài báo thành chuỗi BibTeX.
    
    Returns:
        Chuỗi nội dung file .bib
    """
    header = (
        f"% BibTeX file generated by ScholarSearch\n"
        f"% Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
        f"% Total entries: {len(articles)}\n"
        f"% Compatible with Zotero, Mendeley, LaTeX\n\n"
    )

    entries = [_article_to_bibtex(a) for a in articles]
    return header + "\n\n".join(entries)


def export_bibtex_bytes(articles: List[Article]) -> bytes:
    """Trả về BibTeX dưới dạng bytes để Streamlit download."""
    return export_bibtex(articles).encode("utf-8")


# ---------------------------------------------------------------
# Xuất CSV
# ---------------------------------------------------------------

def export_csv_bytes(articles: List[Article]) -> bytes:
    """
    Xuất danh sách bài báo thành CSV bytes.
    Tương thích với Zotero (RIS import) và Excel.
    """
    if not articles:
        return b""

    rows = [a.to_dict() for a in articles]
    df = pd.DataFrame(rows)

    buffer = io.BytesIO()
    df.to_csv(buffer, index=False, encoding="utf-8-sig")  # utf-8-sig cho Excel tiếng Việt
    return buffer.getvalue()


# ---------------------------------------------------------------
# Xuất Excel
# ---------------------------------------------------------------

def export_excel_bytes(articles: List[Article], citation_style: str = "APA 7th") -> bytes:
    """
    Xuất danh sách bài báo thành Excel (.xlsx) với:
    - Sheet 1: Metadata đầy đủ
    - Sheet 2: Danh sách trích dẫn theo style chọn
    """
    if not articles:
        return b""

    # Sheet 1: Metadata
    rows = [a.to_dict() for a in articles]
    df_meta = pd.DataFrame(rows)

    # Sheet 2: Citations
    citation_formatters = {
        "APA 7th": format_apa_plain,
        "MLA 9th": format_mla,
        "Chicago 17th": format_chicago,
    }
    formatter = citation_formatters.get(citation_style, format_apa_plain)

    citation_rows = []
    for i, article in enumerate(articles, 1):
        citation_rows.append({
            "No.": i,
            "Citation": formatter(article).replace("*", ""),
            "DOI": article.doi,
            "Year": article.display_year,
            "Authors": article.authors_str,
        })
    df_cite = pd.DataFrame(citation_rows)

    # Ghi vào buffer
    buffer = io.BytesIO()
    with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
        df_meta.to_excel(writer, sheet_name="Metadata", index=False)
        df_cite.to_excel(writer, sheet_name=f"{citation_style} Citations", index=False)

        # Điều chỉnh độ rộng cột
        for sheet_name in writer.sheets:
            ws = writer.sheets[sheet_name]
            for col in ws.columns:
                max_len = max(
                    (len(str(cell.value)) for cell in col if cell.value), default=10
                )
                ws.column_dimensions[col[0].column_letter].width = min(max_len + 2, 80)

    return buffer.getvalue()


# ---------------------------------------------------------------
# Xuất APA List (TXT)
# ---------------------------------------------------------------

def export_apa_txt(articles: List[Article], style: str = "APA 7th") -> str:
    """
    Xuất danh sách tài liệu tham khảo dạng văn bản thuần.
    Sắp xếp theo alphabet của tác giả đầu tiên.
    """
    from citation.formatter import format_citation

    # Sắp xếp theo họ tác giả đầu tiên → năm
    sorted_articles = sorted(
        articles,
        key=lambda a: (a.first_author_last.lower(), a.year or 0),
    )

    header = (
        f"REFERENCES ({style})\n"
        f"Generated by ScholarSearch — {datetime.now().strftime('%Y-%m-%d')}\n"
        f"{'=' * 60}\n\n"
    )

    lines = []
    for article in sorted_articles:
        citation = format_citation(article, style).replace("*", "")
        lines.append(citation)

    return header + "\n\n".join(lines)


def export_apa_txt_bytes(articles: List[Article], style: str = "APA 7th") -> bytes:
    """Trả về APA list dưới dạng bytes."""
    return export_apa_txt(articles, style).encode("utf-8")
